name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Compose
        run: docker-compose build

      - name: Run Django Tests
        run: docker-compose run --rm app sh -c "python manage.py test"

      - name: Run Lint
        run: docker-compose run --rm app sh -c "flake8 app"
